version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: inmeta-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=inmetadb
    volumes:
      - mongo_data:/data/db

  localstack:
    image: localstack/localstack:3.4.0
    container_name: inmeta-localstack
    ports:
      - "4566:4566"
    environment:
      - AWS_DEFAULT_REGION=us-east-1

volumes:
  mongo_data: